name = "katelyatv"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# 默认 D1 数据库配置（用于命令行操作）
[[d1_databases]]
binding = "katelyatv"
database_name = "katelyatv"
database_id = "b76ccb54-6da3-46e5-8104-2d34168f88a1"

# 生产环境配置
[env.production]
name = "katelyatv"

# 生产环境 D1 数据库配置
[[env.production.d1_databases]]
binding = "katelyatv"
database_name = "katelyatv"
database_id = "b76ccb54-6da3-46e5-8104-2d34168f88a1"

# 生产环境变量
[env.production.vars]
NEXT_PUBLIC_STORAGE_TYPE = "d1"
NEXT_PUBLIC_SITE_NAME = "katelyatv"
USERNAME = "JQJ"
PASSWORD = "7823099"
NEXT_PUBLIC_ENABLE_REGISTER="true"

# 预览环境配置
[env.preview]
name = "katelyatv-preview"

# 预览环境 D1 数据库配置
[[env.preview.d1_databases]]
binding = "katelyatv"
database_name = "katelyatv"
database_id = "b76ccb54-6da3-46e5-8104-2d34168f88a1"

# 预览环境变量
[env.preview.vars]
NEXT_PUBLIC_STORAGE_TYPE = "d1"
NEXT_PUBLIC_SITE_NAME = "katelyatv"
USERNAME = "JQJ"
PASSWORD = "7823099"
NEXT_PUBLIC_ENABLE_REGISTER="true"

